### ISSUE TITLE
UML Diagram

### ISSUE THREAD

**Issue by tuanvpham** [Visteus/COP4331-Group2-Small-Project#2]
Upload UML Diagram to this issue

**Comment by Visteus** [comment]
[Contact Manager - Class diagram.pdf](https://github.com/Visteus/COP4331-Group2-Small-Project/files/2021163/Contact.Manager.-.Class.diagram.pdf)
[Contact Manager - Use Case Diagram.pdf](https://github.com/Visteus/COP4331-Group2-Small-Project/files/2021164/Contact.Manager.-.Use.Case.Diagram.pdf)
Sorry it took longer than needed for something so simple. Let me know if I'm missing something, but the requirements seem fairly straightforward

**Comment by Visteus** [comment]
[Contact Manager - Class diagram.pdf](https://github.com/Visteus/COP4331-Group2-Small-Project/files/2021188/Contact.Manager.-.Class.diagram.pdf)
Woops, made a small correction to a method in User. 
Was search(Contact), is now searchContact(string)

**Comment by Visteus** [comment]
[Contact Manager - Use Case Diagram.pdf](https://github.com/Visteus/COP4331-Group2-Small-Project/files/2021204/Contact.Manager.-.Use.Case.Diagram.pdf)
Forgot to account for the creation of a new user account, so that's fixed now

**Comment by Visteus** [comment]
[Contact Manager - Class diagram.pdf](https://github.com/Visteus/COP4331-Group2-Small-Project/files/2023530/Contact.Manager.-.Class.diagram.pdf)

**Comment by Visteus** [comment]
[Contact Manager - Class diagram (w Login Manager).pdf](https://github.com/Visteus/COP4331-Group2-Small-Project/files/2023627/Contact.Manager.-.Class.diagram.w.Login.Manager.pdf)
Updated with a login manager class, as suggested by @dduranvz

**Comment by Visteus** [comment]
[Contact Manager - Class diagram - contact-whitelist.pdf](https://github.com/Visteus/COP4331-Group2-Small-Project/files/2028179/Contact.Manager.-.Class.diagram.-.contact-whitelist.pdf)
[Contact Manager - Use Case Diagram.pdf](https://github.com/Visteus/COP4331-Group2-Small-Project/files/2028181/Contact.Manager.-.Use.Case.Diagram.pdf)
